# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.

[Link to Official Documentation](https://docs.scipy.org/doc/numpy/user/)

In [32]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [33]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [34]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2, 4)
8
int64


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** Use **np.identity()** function ]

In [35]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 4x5 with all ones.

[ **Hint: ** Use **np.ones()** function ]

In [36]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Question 3

Create a 2d-array or matrix of order 3x3 with all zeros.

[ **Hint: ** Use **np.zeros()** function ]

In [37]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Question 4

Reverse both the rows and columns of the given matrix.

In [38]:
nd3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(nd3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
np.fliplr(np.flipud(nd3))

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### Question 5

Find the Transpose of nd3.

[ **Hint: ** Use **ndarray.T()** function ]

In [40]:
nd3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Question 6

Flatten the matrix nd3 into 1 single dimension.

[ **Hint: ** Use **ndarray.flatten()** function ]

In [41]:
nd3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Question 7

Concatenate nd3 and nd4(given below).

[ **Hint: ** Use **np.concatenate()** function ]

In [42]:
nd3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
nd4 = np.array([[11,12,13], [14,15,16], [17,18,19]])


In [43]:
np.concatenate((nd3,nd4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Question 8
Square all the elements in the given matrix.

In [44]:
nd5 = np.array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [45]:
np.square(nd5)

array([[  1,   4,   9, 121, 144, 169],
       [ 16,  25,  36, 196, 225, 256],
       [ 49,  64,  81, 289, 324, 361]])

Similarly you can do operations like scalar addition, substraction, division, multiplication (operating on each element in the matrix)

### Question 9

Find the mean of each row in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]


In [46]:
nd6 = np.array([[  1,   4,   9, 121, 144, 169],
       [ 16,  25,  36, 196, 225, 256],
       [ 49,  64,  81, 289, 324, 361]])

In [47]:
np.mean(nd6,axis=1)

array([ 74.66666667, 125.66666667, 194.66666667])

For axis=0 it will give the mean of each column.

### Question 10

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [48]:
nd7 = [[1,2], [3,4]]
nd8 = [[1,1], [1,1]]

In [49]:
np.dot(nd7,nd8)

array([[3, 3],
       [7, 7]])